create table borda (id integer generated by default as identity (start with 1), descricao varchar(255) not null, nome varchar(25) not null, primary key (id));
create table cliente (id integer generated by default as identity (start with 1), nome varchar(255), telefone varchar(255), endereco_id integer, primary key (id));
create table endereco (id integer generated by default as identity (start with 1), bairro varchar(255), numero integer not null, referencia varchar(255), rua varchar(255), primary key (id));
create table item (id integer generated by default as identity (start with 1), observacao varchar(255), quantidade integer not null, tipo_de_pizza varchar(255), id_pizza integer, id_tipo_de_borda integer, item_id bigint, primary key (id));
create table pedido (id bigint generated by default as identity (start with 1), id_cliente integer, id_endereco integer, primary key (id));
create table pizza (id integer generated by default as identity (start with 1), descricao varchar(255), nome varchar(255), primary key (id));
create table precos_pizza (pizza_id integer not null, preco numeric(19,2), tipo_de_pizza varchar(255) not null, primary key (pizza_id, tipo_de_pizza));
alter table cliente add constraint FK64nr9yt889by5lufr1boo5i4s foreign key (endereco_id) references endereco;
alter table item add constraint FKl1mc1p2bvkysl7kdpehcxilf4 foreign key (id_pizza) references pizza;
alter table item add constraint FKcg65dgs68yj58g3s955dx8rir foreign key (id_tipo_de_borda) references borda;
alter table item add constraint FKakmkc1dj5prflrd50ar1ysadf foreign key (item_id) references pedido;
alter table pedido add constraint FK9y4jnyp1hxqa386cnly0ay9uw foreign key (id_cliente) references cliente;
alter table pedido add constraint FK164rat0uf4kkecd0llgbnjsjv foreign key (id_endereco) references endereco;
alter table precos_pizza add constraint FKhq2s96cqcjtdo3gsfis7rx41i foreign key (pizza_id) references pizza;

insert into borda(nome, descricao)values('Alho', 'Deliciosa borda de alho.');
insert into borda(nome, descricao)values('Catupiry', 'Deliciosa borda de catupiry.');
insert into borda(nome, descricao)values('Cream Cheese', 'Deliciosa borda de cream cheese.');

insert into pizza(nome, descricao)values('Mussarela', 'Pizza de mussarela, com rodelas de tomates');
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (1, 'BROTO', 18);
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (1, 'MEDIA', 24);
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (1, 'GRANDE', 30);

insert into pizza(nome, descricao)values('Calabreza', 'Pizza de calabreza, com cebola');
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (2, 'BROTO', 17.50);
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (2, 'MEDIA', 24.90);
insert into precos_pizza (pizza_id, tipo_de_pizza, preco) values (2, 'GRANDE', 29.90);
